title: Jekyll
baseurl: http://localhost
permalink: /:title.html
encoding: "utf-8"
lsi: false

source: source
destination: build

sass:
  style: expanded

markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
